# One CLI to format the code tree - https://github.com/numtide/treefmt
[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]
# Act as an example on how to exclude specific files
excludes = ["examples/nix/sources.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2018"]
includes = ["*.rs"]

[formatter.shell]
command = "/bin/sh"
options = [
  "-euc",
  """
# First lint all the scripts
shellcheck "$@"

# Then format them
shfmt -i 2 -s -w "$@"
    """,
  "--", # bash swallows the second argument when using -c
]
includes = ["*.sh"]
